version: '3.8'

services:
  db:
    build: ./database-service
    ports:
      - "3306:3306"
    volumes:
      - ./database-service/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

  adminer:
    image: adminer
    ports:
      - "8080:8080"
